### ISSUE TITLE
Использование механизма 1C:EDT CLI

### ISSUE THREAD

**Issue by kuzja086** [firstBitMarksistskaya/jenkins-lib#100]
В тестовой версии EDT появился новый механизм ["Интерфейс командной строки 1C:EDT" ](https://its.1c.ru/db/edtdoc#content:10608:hdoc)

**Comment by Kirill** [comment]
1. Собираются уходить от ring
2. Говорят о стабильности.

Проверил на линуксовой машине: ни через ring, ни через 1cedtcli.sh не экспортируются.

**Comment by ovcharenko-di** [comment]
будет реализовано в #133
