### ISSUE TITLE
Локализация замечаний EDT

### ISSUE THREAD

**Issue by Segate-ekb** [firstBitMarksistskaya/jenkins-lib#136]
![image](https://github.com/user-attachments/assets/1e7f83b0-80b8-4207-9c13-593b45e5a940)
Хочется, чтобы текст замечаний был на русском =) Ну а вообще хочется наверное управлять языком вывода замечаний

**Comment by nixel2007** [comment]
Так установи локаль в контейнере своём, не?

**Comment by Segate-ekb** [comment]
да, но для этого надо пр в onec-docker делать )  чтоб по умолчанию было...

**Comment by Segate-ekb** [comment]
https://github.com/firstBitMarksistskaya/onec-docker/pull/57

сделал ПР

**Comment by nixel2007** [comment]
Спасибо!
