### ISSUE TITLE
Определение Версии 

### ISSUE THREAD

**Issue by kuzja086** [firstBitMarksistskaya/jenkins-lib#46]
Сохранил сообщение из какого-то чата в Telegram от Артура Аюханова.

> Пример для общего модуля.
> Для MODULE_PATH нужно указать свой путь к модулю обновления ИБ 
> SET MODULE_PATH=./src/cf/CommonModules/ОбновлениеИнформационнойБазыКАИнфостарт/Ext/Module.bsl
> (grep -Pom1 "(?<=ТекущаяВерсия = "")[^""]+" %MODULE_PATH% > BSL_VERSION.txt) && (set /P BSL_VERSION=< BSL_VERSION.txt) && SET BSL_VERSION
> 
> Далее передача в качестве параметра для запуска проверки SonarQube
> sonar-scanner -Dsonar.host.url=%SONAR_SERVER% -Dsonar.login=%SONAR_TOKEN% -Dsonar.projectVersion=%BSL_VERSION%
> 
> вариант запуска для Windows

Если мы ведем доработку типовой конфигурации, встраиваем доработки через свою подсистему согласно [Документации](https://its.1c.ru/db/bsp315doc#content:4:1:issogl1_обновление_версии_иб), то для сонара можно вытягивать версию оттуда. т.к. версия типовой остается без изменения

**Comment by nixel2007** [comment]
крутая идея!
