### ISSUE TITLE
Добавить поддержку SonarQube без бранч-плагина

### ISSUE THREAD

**Issue by ivanmolodec** [firstBitMarksistskaya/jenkins-lib#60]
На данный момент, если используется SonarQube Community Edition, при шаге проверки сонаром выпадает ошибка

> To use the property "sonar.branch.name" and analyze branches, Developer Edition or above is required

Обойти ошибку возможно, но было бы хорошо иметь поддержку Community Edition "из коробки"

**Comment by otymko** [comment]
Например, можно добавить в шаг sonar-scanner опцию `useBranches` / `useBranch` и по умолчанию отключать. Но это сразу мини breaking changes

**Comment by nixel2007** [comment]
я бы наоборот ее оставил включенной по умолчанию. дабы популяризировать бранч плагин, и чтобы меньше конфигуририть в каждом проекте - плагин один раз поставил и забыл, а джсон надо править всегда.
