### ISSUE TITLE
Добавить проверку перед созданием архива 1Cv8.1CD.zip

### ISSUE THREAD

**Issue by rusdaurov** [firstBitMarksistskaya/jenkins-lib#87]
Если не очищать каталог до/после сборки падает на при создании архива 1Cv8.1CD.zip
![IMG_20220603_184418](https://user-images.githubusercontent.com/26689696/171899751-0a62de40-d829-4400-bcf5-567caf381945.jpg)

**Comment by nixel2007** [comment]
Можешь попробовать в vars/zipInfoBase.groovy добавить следующий код перед операцией zip?
```groovy
    if (fileExits('1Cv8.1CD.zip')) {
        fileOperations([fileDeleteOperation(includes: '1Cv8.1CD.zip')])
    }
```

**Comment by ivanmolodec** [comment]
Для этого правда придется подключить file operations plugin, но можно вот из этой фича-ветки подобрать https://github.com/ivanmolodec/jenkins-lib/tree/feature-edt-validate-settings

**Comment by nixel2007** [comment]
> Для этого правда придется подключить file operations plugin, но можно вот из этой фича-ветки подобрать https://github.com/ivanmolodec/jenkins-lib/tree/feature-edt-validate-settings

Он не нужен в градле в явном виде. Главное чтобы на сервере стоял.

**Comment by rusdaurov** [comment]
![image](https://user-images.githubusercontent.com/26689696/172106700-ddb8d078-e0c9-4f62-9cdf-c85738154d1d.png)
пока так

**Comment by nixel2007** [comment]
Вот я слепошара. fileExists конечно же.

**Comment by rusdaurov** [comment]
Работает, но тут другая беда, 
![image](https://user-images.githubusercontent.com/26689696/172112067-731ec2b2-e32e-4443-9814-9f8ee2ca87d5.png)
и я думаю что лучше, прописать по всем файлам или clean before checkout?

**Comment by ivanmolodec** [comment]
> Работает, но тут другая беда, ![image](https://user-images.githubusercontent.com/26689696/172112067-731ec2b2-e32e-4443-9814-9f8ee2ca87d5.png) и я думаю что лучше, прописать по всем файлам или clean before checkout?

У меня стоит clean before checkout, но если дженкинс на винде, то в некоторых случаях он из-за этого падает с ошибкой т.к. файлы ещё заняты ОС

**Comment by nixel2007** [comment]
> Работает, но тут другая беда, 
> ![image](https://user-images.githubusercontent.com/26689696/172112067-731ec2b2-e32e-4443-9814-9f8ee2ca87d5.png)
> и я думаю что лучше, прописать по всем файлам или clean before checkout?

Лучше прописать по всем файлам, так как clean before checkout в целом может замедлять сборку. Возможно имеет смысл дропать весь каталог build целиком.

**Comment by rusdaurov** [comment]
> > Работает, но тут другая беда,
> > ![image](https://user-images.githubusercontent.com/26689696/172112067-731ec2b2-e32e-4443-9814-9f8ee2ca87d5.png)
> > и я думаю что лучше, прописать по всем файлам или clean before checkout?
> 
> Лучше прописать по всем файлам, так как clean before checkout в целом может замедлять сборку. Возможно имеет смысл дропать весь каталог build целиком.

Вижу в некоторых шагах есть
https://github.com/rusdaurov/jenkins-lib/blob/9fc54dc240b0b5178cc75adfdc76dbdc9e8febe1/src/ru/pulsar/jenkins/library/steps/DesignerToEdtFormatTransformation.groovy#L37

добавить нужно будет в 'pre-stage'?         
dir(path)
deleteDir()
только я не пойму зависим ли мы от текущего каталога дальше и стоит ли его вернуть?

**Comment by rusdaurov** [comment]
и в разных шагах будем удалять почти одно и то же же

**Comment by nixel2007** [comment]
> только я не пойму зависим ли мы от текущего каталога дальше и стоит ли его вернуть?

При каждом выделении агента есть вероятность попасть на протухшие данные в build. Библиотека построена на принципе передачи нужных данных между стейджами через stash, так что думаю, что на каждом выделении агента нужно смотреть, что нужно дропать. Либо дропать целиком build, но тогда это надо задокументировать.

**Comment by rusdaurov** [comment]
ух.. казалось бы

**Comment by rusdaurov** [comment]
пока так
[https://github.com/rusdaurov/jenkins-lib/commit/80996725974229894fbafce1846f7c32857d397d](url)
проверил на шагах которые могу прогнать все зеленное (хотя едт ругается зеленым цветом), остальное затирается при выполнении команды, 
возник вопрос по поводу [https://github.com/firstBitMarksistskaya/jenkins-lib/blob/911be3c7ba4ce3c9c8704dd3dfa6887c21e8552d/vars/pipeline1C.groovy#L82](url),
и наверно стоит при первом выполнении чего либо на агентах удалять build
